### ISSUE TITLE
Add torrent "share" links

### ISSUE THREAD

**Issue by rom1504** [feross/webtorrent-app#215]
When you add *any* torrent in webtorrent-app, it's instantly becomes available in instant.io.

It might be interesting to add a share link to instant.io for that torrent.

edit: it's particularly obvious that it works if you open that torrent in instant.io in the same host since it's seeded in localhost ! (of course localhost is not super useful, but for example sharing the link with someone on your local network could be nice)

---

TODO: (added by @feross)

- [ ] Add "Save Torrent File As..."
- [ ] Add "Copy Magnet Link to Clipboard"
- [ ] Add "Copy Instant.io Link to Clipboard"

**Comment by feross** [comment]
Sure, we can try this out. While we're at it, let's add a few more share options. I like this UI from Transmission:

<img width="242" alt="screen shot 2016-03-24 at 5 21 39 pm" src="https://cloud.githubusercontent.com/assets/121766/14034888/ec3ad324-f1e4-11e5-9511-8088d67534ea.png">

I also think it's fine to bury this in a right-click menu, since this is advanced functionality.
