### ISSUE TITLE
UX polish

### ISSUE THREAD

**Issue by dcposch** [feross/webtorrent-app#3]
- Torrent list
  - [x] Add ability to start and stop torrenting without deleting the torrent
  - [x] Make the + button work
  - [x] Add Blender Foundation torrents for demonstration
  - [x] Play button should turn into a spinner if you click on it before the torrent is ready
- Player controls
  - [ ] Switch from `sequential` to `rarest` strategy once the video has buffered far enough
  - [x] Scrubbing
  - [x] Cast buttons
  - [x] Fullscreen toggle button, ESC to exit fullscreen
  - [x] Letterboxing (video should be centered)
  - [x] Platform polish (back button in title bar in OSX, over video on hover in Linux and Windows)
  - [x] Hide the player controls if the mouse hasn't moved for a while
  - [x] Don't hide the player controls when scrubbing, when moused over them, or when paused
- Cross platform
  - [x] Make it look nice on Ubuntu
  - [x] Make it look nice on Windows

**Comment by ngoldman** [comment]
Currently there are three actions for each torrent in the list -- chromecast, play, and delete.

The video functionality is cool but (currently) only works for single video files. I think a start/pause download button (which may conflict visually with the video play button) is more important since it applies to all types of downloads. I think it should also be more prominent in the visual hierarchy than the video controls.

So here is an emoji mockup:

Current:

title :signal_strength: :arrow_forward: :x:
:zero: % - :zero: Peers - :zero: B/s - :zero: B/s

Proposed changes:

title :arrow_forward: :x:
:signal_strength: :cinema:
:zero: % - :zero: Peers - :zero: B/s - :zero: B/s

- Download controls (first row) are available for all torrents
  - play button turns to pause when active
- Playback controls (second row) are only visible for supported files

If this makes sense to you @feross I can work on implementing it.

**Comment by ChrisMorrisOrg** [comment]
Fullscreen is a bit of an issue in OS X at the moment, the back/forward and add torrent buttons are not accessible in fullscreen mode.

Perhaps having those buttons move into the chrome in fullscreen mode would work better?

**Comment by dcposch** [comment]
@ChrisMorrisOrg i think that's fine. you can hit ESC once to get out of fullscreen, then ESC again (or click back) to return to the torrent list

the add button appears only when you're in the torrent list, not while you're playing a video

**Comment by feross** [comment]
@dcposch What does the app look like on Ubuntu now? Can we check off "make it look nice on Ubuntu?" from the list?

**Comment by rom1504** [comment]
It looks okay in kubuntu currently, apart from #51 

![webtorrent app](https://cloud.githubusercontent.com/assets/2346494/13554723/2fe0cfc2-e3b0-11e5-84e1-2990f24c111a.png)

**Comment by giuscri** [comment]
Pressing the space bar should pause the video

**Comment by dcposch** [comment]
@giuscri good call, i'll make it do that

**Comment by dcposch** [comment]
@feross it looks good in standard Ubuntu. I commented on #51 and I think it's NBD

**Comment by feross** [comment]
Looks good on Windows.



I just discovered some minor UX issues:

- [ ] Don't resize window when player is opened if window is maximized. (Didn't find this because OS X doesn't have the notion of maximized windows, only fullscreen.)
- [ ] Try hiding top menu buttons until user presses Alt
- [ ] Leave fullscreen when player closes. (all OSs)

**Comment by feross** [comment]
<img width="540" alt="screen shot 2016-03-07 at 6 20 44 pm" src="https://cloud.githubusercontent.com/assets/121766/13590015/549cef08-e491-11e5-8cef-98de21d71a0b.png">

**Comment by feross** [comment]
Going to close this issue now.

@dcposch There's already an issue open on the webtorrent repo for the one remaining item.

'sequential' piece selection should be a better citizen: https://github.com/feross/webtorrent/issues/375
