### ISSUE TITLE
move player to separate window

### ISSUE THREAD

**Issue by ungoldman** [feross/webtorrent-app#5]
I think it would be beneficial to move the video player to a separate window so that a user can see everything in the list and have one or more video players open simultaneously. This would simplify managing state for the list window too.

If you think it's worth doing, I can take a crack at it.

**Comment by ChrisMorrisOrg** [comment]
I would like to be able to see my list of torrents while streaming a video too. Not really sure if this is preferable in terms of UX and code maintenance, but what if the user can open a video in a new window when they double-click on a torrent, but keep it within the window if they single-click the play button? Might add unnecessary complexity that way, though. The only reason I throw that idea out there is because I like to try keeping things in a single window unless I really need to open another one.

If I had to choose one or the other, I'd prefer videos to open in a new window. Functionality > form.

**Comment by feross** [comment]
I think we should come back to this idea for WebTorrent v2. Right now I want to get something shipped ASAP and I like the idea of keeping v1 really simple so we can focus on making it rock solid and reliable.
