### ISSUE TITLE
Add support for magnetURIs

### ISSUE THREAD

**Issue by giuscri** [feross/webtorrent-app#54]
Some trackers make **super** easy to obtain magnet links compared to download the `.torrent`'s.

Adding support for them would be very useful. (:

**Comment by ngoldman** [comment]
Will be adding support for magnet links and URLs soon

**Comment by feross** [comment]
There is already support for magnet links! Just paste them with Cmd+V or Ctrl+V and you're all set!

**Comment by ngoldman** [comment]
Oh hidden feature! Might be good to add a mini dialog box to enter a URL/magnet link/info hash/file path as an option on the `+` button too

**Comment by feross** [comment]
@ngoldman Yeah, we definitely need better/more UI for this, but there's already a placeholder menu option in File for adding a torrent address (will support magnet links, http/https urls, even file system urls).

And in the Edit menu, the paste option also says "Paste Torrent Address". :)

**Comment by iadj** [comment]
I'd also recommend the ability to set `webtorrent-app` as the default app for opening magnet files on the OS.

And, while we're at it, a custom protocol i.e. `wbt://<magnet>` would be great!

**Comment by feross** [comment]
@iadj I'm going to open a separate issue for your first request, since it's good: https://github.com/feross/webtorrent-app/issues/77

Regarding the custom protocol handler, why is that desirable if WebTorrent is already set as the default handler for magnet links?

**Comment by feross** [comment]
@ngoldman Opened an explicit issue for your request: https://github.com/feross/webtorrent-app/issues/78

Going to close this now, since the app already supports magnet links!

**Comment by iadj** [comment]
@feross Since torrent streaming isn't supported by most popular torrent managers, developers and websites could make an integration for this without requiring users to rethink their default torrent configurations.
Websites that share torrent files generally have links like 'Download Torrent' and 'Open Magnet'. Imagine an extra link saying 'Stream Torrent'. That's what I'd like to see happening. Bonus suggestion: decide on a general torrent streaming protocol (i.e. `str://<magnet>`) with https://github.com/jaruba/PowderPlayer so that developers can simply add 'Stream Torrent` links that support any torrent app with the protocol!

**Comment by feross** [comment]
@iadj Moved your suggestion to a new issue: https://github.com/feross/webtorrent-app/issues/83
