### ISSUE TITLE
Application does not start torrenting anymore

### ISSUE THREAD

**Issue by giuscri** [feross/webtorrent-app#67]
Apparently in commit [`093d810`](https://github.com/feross/webtorrent-app/commit/093d810b90dfc4b61a5b8f5b5a05eb9c58f3d6c6), `WebTorrent.add()` is called using the torrent's infoHash while the API need the magnetURI.

**Comment by ngoldman** [comment]
I think @dcposch changed the way torrent information is stored quite a bit since yesterday, you may have to manually delete the application config.


Platform | Location
--- | ---
OS X | `~/Library/Application Support/<name>/config.json`
Linux (XDG) | `$XDG_CONFIG_HOME/<name>/config.json`
Linux (Legacy) | `~/.config/<name>/config.json`
Windows (> Vista) | `%LOCALAPPDATA%/<name>/config.json`
Windows (XP, 2000) | `%USERPROFILE%/Local Settings/Application Data/<name>/config.json`

I tested what's on master and it's still working for me, but I was working on it yesterday too and cleared the config multiple times. Sorry! Remember this is under active development and unreleased so There Will Be Bugs :)

**Comment by giuscri** [comment]
Ok. Application works again after a
```
$ rm ~/.config/WebTorrent/config.json
```
