### ISSUE TITLE
Tests?

### ISSUE THREAD

**Issue by giuscri** [feross/webtorrent-app#92]

**Comment by feross** [comment]
The underlying `webtorrent` library already has really good test coverage. See here: https://github.com/feross/webtorrent/tree/master/test

If you want to help improve things, you can add additional tests there. There are even a few open test-related issues you can take a look at: https://github.com/feross/webtorrent/issues?q=is%3Aissue+is%3Aopen+label%3Atest

But, as for this application, we definitely don't need UI tests. Those are almost always over-engineered, brittle, and just not worth the trouble since the app is trivially testable just by using it for a few minutes, which is easy to do before a release.

I'm okay with unit tests for the configuration loading and other stuff that doesn't touch the UI/Electron code.

**Comment by feross** [comment]
Honestly, any part of this app that could be unit tested should probably get pulled out into it's own npm package with it's own tests. Gonna close tihs.
